### PR TITLE
CMake builds

### PR DESCRIPTION
**Pull request by sunsided**
This pull request adds `CMakeLists.txt` from [LuaDist](https://github.com/LuaDist/libjpeg) project for CMake builds.

### CODE REVIEW

**Comment by ghost** [comment]
Where is CMakeLists.txt? I can't find it in https://github.com/LuaDist/libjpeg either.

**Comment by sunsided** [comment]
Not sure I understand the question. Check the `Files changed` tab, it's the first file. :sweat_smile: [Here's](https://github.com/sunsided/libjpeg/blob/63604299f28287657cebebd03f2c376e84f34d98/CMakeLists.txt) the version I was asking to pull.

**Comment by ghost** [comment]
Usually CMake support is integrated in the source package. So why not just put CMakeLists.txt (and possibly other cmake things) into the libjpeg source package, instead of hiding it in Pull requests -> Files changed? Well, I admit I really don't know that; I only know "cd build" and "cmake ..".

**Comment by sunsided** [comment]
That is precisely what this pull request is about, it just wasn't merged yet. :)

**Comment by ghost** [comment]
I see. I had thought you are the developer and here is the official github site of libjpeg.

**Comment by sunsided** [comment]
Sadly no. :sweat_smile:

**Comment by weltling** [comment]
@sunsided many thanks for the PR, unfortunately it was overlooked :/ Anyways, my question is - why don't you target the mainstream? The sources here are dedicated to windows and nmake is usually enough to get the job done. Windows specific patches are sometimes required, so they're maintained along with the vanilla sources. Unlike this PR, suggesting to carry something not absolutely required for a Windows build. I really think it's better you send this patch upstream.

Thanks.

**Comment by sunsided** [comment]
Well, CMake is my main build system (regardless of the platform) and I needed support for this library back then. :man_shrugging: :sweat_smile:

**Comment by cmb69** [comment]
Oh, seems I'm late to the party, but this PR is now obsolete, since we switched to libjpeg-turbo which has CMake support out of the box. Thanks for your PR anyway!

**Pull request closed without merging**
