### PR TITLE
Win: build libjpeg as a dll

### PR DESCRIPTION
**Pull request by CristiFati**
More details on: [[SO]: How to build a DLL version of libjpeg 9b? (@CristiFati's answer)](https://stackoverflow.com/questions/44450813/how-to-build-a-dll-version-of-libjpeg-9b/44469099#44469099)

### CODE REVIEW

**Comment by weltling** [comment]
Thanks for the PR. For the implementation - I'd recommend doing it through a def file, so no code needs to be touched but the makefile only. But works this way, too. This kind of patch should be integrated mainstream, please send it there first. For PHP we always use static libs. 

Thanks.

**Comment by CristiFati** [comment]
In the *.def* file I'd have to list every function. :) . I'm sorry, but what's mainstream? Is this repo forked from another? If yes, I can't (or don't know how to) see it.

**Comment by weltling** [comment]
The mainstream homepage is linked from README http://www.ijg.org/. The winlibs org is for maintaining the dependency sources for [PHP](https://github.com/php/php-src). We provide also pre compiled bins here https://windows.php.net/downloads/php-sdk/deps/.

For .def - yes, it needs every single function, which is almost a one liner to generate :) But it makes it much easier to maintain as no actual sources have to be touched.

Thanks.

**Comment by CristiFati** [comment]
Thank you for the info. I tried contacting them but I couldn't (besides their webpage looking like 30 years ago), when trying to contact them it appears to wait forever.

I could not not notice the reticence of modifying code :). I understand it could bring an extra level of complexity, but it's one line in a file that doesn't get changed often. Note that the *.def* file could also be considered as  source.

Anyway, it probably doesn't bring any value to your purposes, but anyway if anyone will need it it's here as well.

Regards,
Cristi Fati.

**Pull request closed without merging**
